### ISSUE TITLE
Sign up issues

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/unified-extension#4] opened 2016-06-18 08:43 UTC
Users are struggling to sign up

**Comment by Steven-Eardley** [comment] 2016-07-16 10:45
Handled via website. There is a link on the extension options page for users to register or sign in to get their API Key.

**Comment by Steven-Eardley** [comment] 2016-07-16 10:46
Closing. Duplicate of issue #2 (from extension's perspective)

**Closed by Steven-Eardley** 2016-07-16 10:46 UTC
Labels: enhancement, JISC
